name: Check and Update

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间午夜运行
  workflow_dispatch: # 允许手动触发

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch and check for updates from upstream
        id: check
        run: |
          git remote add upstream https://github.com/SzeMeng76/LunaTV.git
          git fetch upstream
          if [[ $(git rev-parse HEAD) != $(git rev-parse upstream/main) ]]; then
            echo "Updates found. Pulling changes..."
            git pull --ff-only upstream main
            echo "::set-output name=has_updates::true"
          else
            echo "No updates found."
            echo "::set-output name=has_updates::false"
          fi

      - name: Login to Docker Hub
        if: steps.check.outputs.has_updates == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.check.outputs.has_updates == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lunatv:latest # 请将 username 替换为你的 Docker Hub 用户名
